control_manager:
    ros__parameters:
        controllers:
            - forward_command_controller_position

        forward_command_controller_position:
            type: forward_command_controller/ForwardCommandControllerNewComponents

forward_command_controller_position:
    ros__parameters:
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4
            - joint_5
            - joint_6
        interface_name: position
